# Generated by Django 5.0.6 on 2024-06-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmin',
            name='AdminSname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
