# Generated by Django 5.0.6 on 2024-06-12 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schooladmin_adminsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfacility',
            name='school_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schooladmin'),
        ),
    ]
