# Generated by Django 5.0.6 on 2024-06-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_sfacility_school_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfacility',
            name='school_admin',
        ),
    ]
