# Generated by Django 5.0.6 on 2024-06-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_sfacility_school_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='FacilityCategory',
            field=models.CharField(choices=[('F1class', 'F1class'), ('f2class', 'f2class'), ('f3class', 'f3class'), ('f4class', 'f4class'), ('Offices', 'Offices'), ('Laboratory', 'Laboratory'), ('Library', 'Library'), ('Toilets', 'Toilets'), ('Water', 'Water'), ('Sports', 'Sports')], default='Classes', max_length=100),
        ),
        migrations.AlterField(
            model_name='sfacility',
            name='FacilityCategory',
            field=models.CharField(choices=[('F1class', 'F1class'), ('f2class', 'f2class'), ('f3class', 'f3class'), ('f4class', 'f4class'), ('Offices', 'Offices'), ('Laboratory', 'Laboratory'), ('Library', 'Library'), ('Toilets', 'Toilets'), ('Water', 'Water'), ('Sports', 'Sports')], default='Classes', max_length=100),
        ),
    ]
