# Generated by Django 5.0.6 on 2024-06-12 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_facility_facilitycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanance',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='school.sfacility'),
        ),
        migrations.AlterField(
            model_name='sfacility',
            name='FacilityCategory',
            field=models.CharField(choices=[('F1class', 'F1class'), ('f2class', 'f2class'), ('f3class', 'f3class'), ('f4class', 'f4class'), ('Offices', 'Offices'), ('Laboratory', 'Laboratory'), ('Library', 'Library'), ('Toilets', 'Toilets'), ('Water', 'Water'), ('Sports', 'Sports')], default='F1class', max_length=100),
        ),
    ]
