# Generated by Django 5.0.6 on 2024-06-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_maintanance_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
