# Generated by Django 5.0.6 on 2024-06-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_maintanance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintanance',
            name='status',
        ),
    ]
