# Generated by Django 5.0.6 on 2024-06-17 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_maintanance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='TimePosted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
