# Generated by Django 5.0.6 on 2024-06-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_announcement_timeposted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
