# Generated by Django 5.0.6 on 2024-06-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_delete_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dschool',
            name='DistrictName',
        ),
        migrations.AlterField(
            model_name='sfacility',
            name='FacilityCategory',
            field=models.CharField(choices=[('F1class', 'F1class'), ('f2class', 'f2class'), ('f3class', 'f3class'), ('f4class', 'f4class'), ('Offices', 'Offices'), ('Laboratory', 'Laboratory'), ('Library', 'Library'), ('Toilets', 'Toilets'), ('Water', 'Water'), ('Sports', 'Sports'), ('Others', 'Others')], default='F1class', max_length=100),
        ),
    ]
