# Generated by Django 5.0.6 on 2024-06-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_dschool_districtname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfacility',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='school.dschool'),
        ),
    ]
