# Generated by Django 5.0.6 on 2024-06-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_sfacility_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanance',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
