# Generated by Django 5.0.6 on 2024-06-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_maintanance_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanance',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_receipts/'),
        ),
    ]
