# Generated by Django 5.0.6 on 2024-06-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_maintanance_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
