# Generated by Django 5.0.6 on 2024-07-09 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_maintanance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='DSchoolID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.dschool'),
        ),
    ]
