# Generated by Django 5.0.6 on 2024-07-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_announcement_dschoolid'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
