# Generated by Django 5.0.6 on 2024-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_announcement_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='comments',
        ),
        migrations.AddField(
            model_name='announcement',
            name='Comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
