from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='district-login'),
    path('school/', views.index, name='school-index'),
    path('addadmin/', views.addadmin, name='school-addadmin'),
    path('addschool/', views.addschool, name='school-addschool'),
    path('addschool/edit/<int:pk>/', views.addschool_edit, name='school-addschool-edit'),
    path('addschool/delete/<int:pk>/', views.addschool_delete, name='school-addschool-delete'),
    path('addadmin/delete/<int:pk>/', views.addadmin_delete, name='school-addadmin-delete'),
    path('addadmin/edit/<int:pk>/', views.addadmin_edit, name='school-addadmin-edit'),
    path('viewitems/', views.viewitems, name='school-viewitems'),
    path('payment/', views.payment, name='school-payment'),
    path('maintanance2/', views.maintanance2, name='school-maintanance2'),
    path('paymentreport/', views.paymentreport, name='school-paymentreport'),
    path('viewmonthlyreport/', views.viewmonthlyreport, name='school-viewmonthlyreport'),
    path('register/', views.register, name='district-register'),
    path('profile/', views.profile, name='district-profile'),
    path('profile/update/', views.profile_update, name='district-profile-update'),
    
    path('profile2/', views.profile2, name='district-profile2'),
    path('profile2/update2/', views.profile_update2, name='district-profile-update2'),
    path('change_password/', views.change_password_view, name='change_password'),
    path('change_password2/', views.change_password_view2, name='change_password2'),
    
    path('logout/', views.logout_view, name='district-logout'),
    path('addannouncement/', views.addannouncement, name='school-addannouncement'),
    path('viewannouncement/', views.viewannouncement, name='school-viewannouncement'),
    path('view_comments/', views.view_comments, name='view_comments'),
    path('edit-announcement/<int:pk>/', views.editannouncement, name='edit-announcement'),
    path('delete-announcement/<int:pk>/', views.deleteannouncement, name='delete-announcement'),
    
    path('addfacility/', views.addfacility, name='school-addfacility'),
    path('facility/<int:facility_id>/qr/', views.generate_qr_code, name='generate_qr_code'),
    path('editfacility/<int:pk>/', views.editfacility, name='edit-facility'),
    path('deletefacility/<int:pk>/', views.deletefacility, name='delete-facility'),
    path('addmaintainance/', views.addmaintainance, name='school-addmaintainance'),
    path('admin_paymentstatus/', views.admin_paymentstatus, name='school-admin_paymentstatus'),
    path('schooladmin_index/', views.schooladmin_index, name='school-schooladmin_index'),
    path('maintanance/', views.maintanance, name='schooladmin-maintanance'),
    path('maintanance/edit/<int:maintenance_id>/', views.edit_maintenance, name='edit_maintenance'),
    path('maintanance/delete/<int:maintenance_id>/', views.delete_maintenance, name='delete_maintenance'),
    path('generate-pdf/', views.generate_pdf, name='generate_pdf'),
    path('maintanance/download/', views.download_maintenance_records, name='download_maintenance_records'),
    path('download_payment_records/', views.download_payment_records, name='download_payment_records'),
    path('download_facilities_excel/', views.download_facilities_excel, name='download_facilities_excel'),
    path('download_maintenance_excel/', views.download_maintenance_excel, name='download_maintenance_excel'),
    path('download_paymentstatus_excel/', views.download_paymentstatus_excel, name='download_paymentstatus_excel'),
]
